import { CreditPassportInputs } from './types';

export const defaultPassportInputs: CreditPassportInputs = {
  businessIdentity: {
    name: 'Wathaci Demo Traders',
    registrationNumber: '1209482-ZM',
    incorporationDate: '2019-02-10',
    sector: 'Retail',
    subsector: 'Fast Moving Consumer Goods',
    location: 'Lusaka, Zambia',
    ownership: {
      women: 60,
      youth: 30,
      local: 90,
      foreign: 10,
    },
  },
  financials: {
    annualRevenue: [1200000, 1500000, 1920000],
    monthlyRevenue: [120000, 135000, 150000, 142000, 162000, 178000],
    profitMargin: 18,
    cashflowStability: 72,
    averageInvoiceValue: 3200,
    cashConversionCycle: 45,
    negativeBalanceFrequency: 2,
    debtServiceCoverage: 1.4,
    ebitdaMargin: 22,
    customerConcentration: 30,
  },
  banking: {
    monthlyBankVolume: 850000,
    mobileMoneyVolume: 420000,
    cardPaymentsVolume: 310000,
    salesChannels: ['mobile_money', 'pos', 'online', 'wholesale'],
    loanHistory: 'Term loan and overdraft repaid on time',
    repaymentHistory: 78,
    rejectionHistory: 1,
    overdraftFrequency: 1,
    chequeBounceHistory: 0,
  },
  compliance: {
    taxRegistration: true,
    taxClearance: true,
    annualReturns: true,
    businessInsurance: true,
    licenses: ['Trading License', 'ZRA Tax Clearance'],
    policyCoverage: 70,
  },
  behavioral: {
    profileCompletion: 90,
    engagement: 76,
    responsiveness: 82,
    dataFreshness: 74,
    marketplacePerformance: 80,
    paymentTimeliness: 88,
  },
  digitalOperational: {
    digitalFootprint: 72,
    erpUsage: 55,
    deliveryReliability: 70,
    customerSatisfaction: 78,
    supplyChainRisk: 35,
    currencyExposure: 40,
    seasonality: 25,
    continuityPlans: 60,
  },
  operations: {
    supplyChainRisk: 35,
    currencyExposure: 40,
    seasonality: 25,
    continuityPlans: 60,
  },
};
