BEGIN;

-- Align public.profiles with onboarding payloads and UI expectations
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS middle_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS msisdn text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS coordinates jsonb,
  ADD COLUMN IF NOT EXISTS profile_image_url text,
  ADD COLUMN IF NOT EXISTS linkedin_url text,
  ADD COLUMN IF NOT EXISTS registration_number text,
  ADD COLUMN IF NOT EXISTS industry_sector text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS website_url text,
  ADD COLUMN IF NOT EXISTS employee_count integer,
  ADD COLUMN IF NOT EXISTS annual_revenue numeric,
  ADD COLUMN IF NOT EXISTS funding_stage text,
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS payment_phone text,
  ADD COLUMN IF NOT EXISTS use_same_phone boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS card_details jsonb,
  ADD COLUMN IF NOT EXISTS investment_focus text,
  ADD COLUMN IF NOT EXISTS investment_ticket_min numeric,
  ADD COLUMN IF NOT EXISTS investment_ticket_max numeric,
  ADD COLUMN IF NOT EXISTS investment_stage text,
  ADD COLUMN IF NOT EXISTS investment_regions text,
  ADD COLUMN IF NOT EXISTS impact_focus text,
  ADD COLUMN IF NOT EXISTS support_services text,
  ADD COLUMN IF NOT EXISTS support_preferences text,
  ADD COLUMN IF NOT EXISTS partnership_preferences text,
  ADD COLUMN IF NOT EXISTS donor_type text,
  ADD COLUMN IF NOT EXISTS funding_focus text,
  ADD COLUMN IF NOT EXISTS annual_funding_budget numeric,
  ADD COLUMN IF NOT EXISTS institution_type text,
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS government_focus text,
  ADD COLUMN IF NOT EXISTS programs text,
  ADD COLUMN IF NOT EXISTS partnership_needs text,
  ADD COLUMN IF NOT EXISTS qualifications jsonb,
  ADD COLUMN IF NOT EXISTS experience_years integer,
  ADD COLUMN IF NOT EXISTS specialization text,
  ADD COLUMN IF NOT EXISTS gaps_identified text[],
  ADD COLUMN IF NOT EXISTS accepted_terms boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS newsletter_opt_in boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS grace_period_access boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS grace_period_started_at timestamptz,
  ADD COLUMN IF NOT EXISTS grace_period_expires_at timestamptz;

-- Refresh PostgREST cache so clients immediately see the updated columns
NOTIFY pgrst, 'reload schema';

COMMIT;

-- Down
BEGIN;
ALTER TABLE public.profiles
  DROP COLUMN IF EXISTS business_name,
  DROP COLUMN IF EXISTS first_name,
  DROP COLUMN IF EXISTS middle_name,
  DROP COLUMN IF EXISTS last_name,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS msisdn,
  DROP COLUMN IF EXISTS country,
  DROP COLUMN IF EXISTS city,
  DROP COLUMN IF EXISTS address,
  DROP COLUMN IF EXISTS coordinates,
  DROP COLUMN IF EXISTS profile_image_url,
  DROP COLUMN IF EXISTS linkedin_url,
  DROP COLUMN IF EXISTS registration_number,
  DROP COLUMN IF EXISTS industry_sector,
  DROP COLUMN IF EXISTS description,
  DROP COLUMN IF EXISTS website_url,
  DROP COLUMN IF EXISTS employee_count,
  DROP COLUMN IF EXISTS annual_revenue,
  DROP COLUMN IF EXISTS funding_stage,
  DROP COLUMN IF EXISTS payment_method,
  DROP COLUMN IF EXISTS payment_phone,
  DROP COLUMN IF EXISTS use_same_phone,
  DROP COLUMN IF EXISTS card_details,
  DROP COLUMN IF EXISTS investment_focus,
  DROP COLUMN IF EXISTS investment_ticket_min,
  DROP COLUMN IF EXISTS investment_ticket_max,
  DROP COLUMN IF EXISTS investment_stage,
  DROP COLUMN IF EXISTS investment_regions,
  DROP COLUMN IF EXISTS impact_focus,
  DROP COLUMN IF EXISTS support_services,
  DROP COLUMN IF EXISTS support_preferences,
  DROP COLUMN IF EXISTS partnership_preferences,
  DROP COLUMN IF EXISTS donor_type,
  DROP COLUMN IF EXISTS funding_focus,
  DROP COLUMN IF EXISTS annual_funding_budget,
  DROP COLUMN IF EXISTS institution_type,
  DROP COLUMN IF EXISTS department,
  DROP COLUMN IF EXISTS government_focus,
  DROP COLUMN IF EXISTS programs,
  DROP COLUMN IF EXISTS partnership_needs,
  DROP COLUMN IF EXISTS qualifications,
  DROP COLUMN IF EXISTS experience_years,
  DROP COLUMN IF EXISTS specialization,
  DROP COLUMN IF EXISTS gaps_identified,
  DROP COLUMN IF EXISTS accepted_terms,
  DROP COLUMN IF EXISTS newsletter_opt_in,
  DROP COLUMN IF EXISTS grace_period_access,
  DROP COLUMN IF EXISTS grace_period_started_at,
  DROP COLUMN IF EXISTS grace_period_expires_at;
COMMIT;
